UMS/urls.py
from django.contrib import admin
from django.urls import path, include
from coreApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('coreApp/',include('coreApp.urls')),
    path('', views.landing, name='landing'),
    path('Uni_admin/', views.admin, name='admin'),
    path('Instructor/', views.instructor, name='instructor'),
    path('Student/', views.course_section, name='student'),
]

coreApp/urls.py
# coreApp/urls.py

from django.urls import path
from . import views

app_name = 'coreApp'  # Specify the app namespace

urlpatterns = [
    path('roster/', views.prof_stats, name='prof_stats'),  # Assign a name to the URL pattern
    path('namesort/', views.sort_prof_name, name='sort_prof_name'),  # Assign a name to the URL pattern
    path('deptsort/', views.sort_prof_dept, name='sort_prof_dept'),
    path('salarysort/', views.sort_prof_salary, name='sort_prof_salary'),
    path('salary_stats/', views.salary_statistics_by_department, name='salary_statistics_by_department'),
    path('performance/', views.performance, name='performance'),
    path('professor_sections/', views.professor_sections, name='professor_sections'),
    path('student_list/', views.student_list, name='student_list'),
    path('course_section/', views.course_section, name='course_section'),
    
   
]

coreApp/forms.py
from django import forms
from .models import Department


class Form(forms.Form):

    name =forms.CharField(label='Name', max_length=200, required=False,
                           widget= forms.TextInput
                           (attrs={
                               'class': 'wiki-title',
                               'name': 'WikiTitle',
                               'placeholder':'Enter Name',
                               'required': 'True'
                            }))
    year=forms.IntegerField(label="Year", required=False,
                           widget= forms.NumberInput
                           (attrs={
                               'class': 'wiki-title',
                               'name': 'WikiTitle',
                               'placeholder':'Enter Year',
                               'required': 'True'
                            }))
    semester = forms.IntegerField(label="Semster",required=False,
                           widget= forms.NumberInput
                           (attrs={
                               'class': 'wiki-title',
                               'name': 'WikiTitle',
                               'placeholder':'Enter Semester',
                               'required': 'True'
                            }))

class StudentListForm(forms.Form):

    name =forms.CharField(label='Name', max_length=200, required=False,
                           widget= forms.TextInput
                           (attrs={
                               'class': 'wiki-title',
                               'name': 'WikiTitle',
                               'placeholder':'Enter Name',
                               'required': 'True'
                            }))
    course = forms.CharField(label="Course",required=False,
                           widget= forms.TextInput
                           (attrs={
                               'class': 'wiki-title',
                               'name': 'WikiTitle',
                               'placeholder':'Enter Course',
                               'required': 'True'
                            }))
    section=forms.CharField(label="Section", required=False,
                           widget= forms.TextInput
                           (attrs={
                               'class': 'wiki-title',
                               'name': 'WikiTitle',
                               'placeholder':'Enter Section',
                               'required': 'True'
                            }))
    semester = forms.IntegerField(label="Semester",required=False,
                           widget= forms.NumberInput
                           (attrs={
                               'class': 'wiki-title',
                               'name': 'WikiTitle',
                               'placeholder':'Enter Semester',
                               'required': 'True'
                            }))
    year=forms.IntegerField(label="Year", required=False,
                           widget= forms.NumberInput
                           (attrs={
                               'class': 'wiki-title',
                               'name': 'WikiTitle',
                               'placeholder':'Enter Year',
                               'required': 'True'
                            }))
    

class DepartmentForm(forms.Form):
    department = forms.ModelChoiceField(
        queryset=Department.objects.all(),
        empty_label=None
    )
    year=forms.IntegerField(label="Year", required=False,
                           widget= forms.NumberInput
                           (attrs={
                               'class': 'wiki-title',
                               'name': 'WikiTitle',
                               'placeholder':'Enter Year',
                               'required': 'True'
                            }))
    semester = forms.IntegerField(label="Semster",required=False,
                           widget= forms.NumberInput
                           (attrs={
                               'class': 'wiki-title',
                               'name': 'WikiTitle',
                               'placeholder':'Enter Semester',
                               'required': 'True'
                            }))

coreApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Student, Instructor,Teaches,Section,ProfessorFunding,Publication
from django.db.models import Avg,Min,Max,F,Count
from django.db import connection
from .forms import Form,StudentListForm,DepartmentForm
from datetime import date

#===============navigation=======================
def landing(request):
    return render(request, 'landing.html')

def admin(request):
    return render(request, 'admin.html')

def instructor(request):
    return render(request, 'instructor.html')

def student(request):
    return render(request, 'student.html')

#====================================PROFESSOR FUNCTIONALITIES===================================================
#============================INSTRUCTOR STATS (ADMIN)=========================
def dictfetchall(cursor):
    "Returns all rows from a cursor as a dict"
    desc = cursor.description
    return [
        dict(zip([col[0] for col in desc], row))
        for row in cursor.fetchall()
    ]
def prof_stats(request):
    cursor = connection.cursor()
    try:
        query = "SELECT * FROM Instructor;"
        cursor.execute(query)
        prof = dictfetchall(cursor)
    finally:
        cursor.close()

    context = {
        'prof': prof
    }
    return render(request, 'roster.html', context)


def sort_prof_name(request):
    cursor = connection.cursor()
    try:
        query = "SELECT * FROM Instructor order by name;"
        cursor.execute(query)
        prof = dictfetchall(cursor)
    finally:
        cursor.close()

    context = {
        'prof': prof
    }
    return render(request, 'roster.html', context)

def sort_prof_dept(request):
    cursor = connection.cursor()
    try:
        query = "SELECT * FROM Instructor order by dept_name;"
        cursor.execute(query)
        prof = dictfetchall(cursor)
    finally:
        cursor.close()

    context = {
        'prof': prof
    }
    return render(request, 'roster.html', context)

def sort_prof_salary(request):
    cursor = connection.cursor()
    try:
        query = "SELECT * FROM Instructor order by salary;"
        cursor.execute(query)
        prof = dictfetchall(cursor)
    finally:
        cursor.close()

    context = {
        'prof': prof
    }
    return render(request, 'roster.html', context)

#=================SALARY STATS (ADMIN)================================
def salary_statistics_by_department(request):
    salary_stats_by_dept = Instructor.objects.values('dept_name').annotate(
        min_salary=Min('salary'),
        max_salary=Max('salary'),
        avg_salary=Avg('salary')
    ).order_by('dept_name')
    
    return render(request, 'salary_stats.html', {'salary_stats_by_dept': salary_stats_by_dept})

#================================PERFORMANCE (ADMIN)==============================================
from datetime import date

def performance(request):

    start_date = None  # Default value for start_date
    end_date = None  # Default value for end_date

    if request.method == 'POST':
        form = Form(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            year = form.cleaned_data["year"]
            semester = form.cleaned_data["semester"]

            if semester == '2':
                start_date = date(year, 1, 1)
                end_date = date(year, 5, 31)
            elif semester == '1':
                start_date = date(year, 8, 1)
                end_date = date(year, 12, 31)

            cursor = connection.cursor()
            try:
                instructor = Instructor.objects.get(name=name)

                # Query to count the number of course sections taught by the instructor
                num_sections_taught = '''
                    SELECT COUNT(*)
                    FROM Section
                    WHERE EXISTS (
                        SELECT course_id
                        FROM Teaches
                        WHERE teacher_id = %s
                        AND Teaches.course_id = Section.course_id
                    )
                    AND semester = %s
                    AND year = %s;
                '''
                with connection.cursor() as cursor:
                    cursor.execute(num_sections_taught, [instructor.id, semester, year])
                    row_section = dictfetchall(cursor)[0]['COUNT(*)']  # Fetch one row

                # Query to calculate the sum of capacities for sections taught by the instructor
                query_capacity = '''
                    SELECT SUM(capacity)
                    FROM Section
                    WHERE EXISTS (
                        SELECT course_id
                        FROM Teaches
                        WHERE teacher_id = %s
                        AND Teaches.course_id = Section.course_id
                    )
                    AND semester = %s
                    AND year = %s;
                '''
                with connection.cursor() as cursor:
                    cursor.execute(query_capacity, [instructor.id, semester, year])
                    row_capacity = cursor.fetchone()  # Fetch one row
                    # Extract capacity value from row_capacity (convert Decimal to int)
                    row_capacity_value = int(row_capacity[0]) if row_capacity and row_capacity[0] is not None else None

                # Query to funding the professor has secured
                query_funding = '''
                    SELECT SUM(funding)
                    FROM Professor_Funding
                    WHERE p_id = %s
                    AND start_date <= %s 
                    AND end_date >= %s;
                '''
                with connection.cursor() as cursor:
                    cursor.execute(query_funding, [instructor.id, end_date, start_date])
                    funding = cursor.fetchone()[0]  # Fetch one row

                # Query number of papers the professor has published
                query_publishing = '''
                    SELECT COUNT(title)
                    FROM Publication
                    WHERE p_id = %s
                    AND date <= %s 
                    AND date >= %s;
                '''
                with connection.cursor() as cursor:
                    cursor.execute(query_publishing, [instructor.id,end_date, start_date])
                    publishing = cursor.fetchone()[0]  # Fetch one row

                # Prepare context data to pass to the template
                context = {
                    'form': form,
                    'id': instructor.id,
                    'name': name,
                    'year': year,
                    'semester': semester,
                    'funding': funding,
                    'publishing': publishing,
                    'row_section': row_section,
                    'row_capacity': row_capacity_value,  # Convert Decimal object to int
                }

                return render(request, 'performance.html', context)

            except Instructor.DoesNotExist:
                return render(request, 'performance.html', {"result": -1, "form": form})
                # Handle the case when the instructor does not exist

    else:
        form = Form()

    # Render the form without results initially
    return render(request, 'performance.html', {'form': form})

#====================================PROFESSOR FUNCTIONALITIES===================================================
def professor_sections(request):
    if request.method == 'POST':
        form = Form(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            year = form.cleaned_data["year"]
            semester = form.cleaned_data["semester"]
            
            cursor = connection.cursor()
            try:
                instructor = Instructor.objects.get(name=name)
                query = '''
                   SELECT *
                   FROM Section
                   WHERE EXISTS (
                       SELECT course_id
                       FROM Teaches
                       WHERE teacher_id = %s
                       AND Teaches.course_id = Section.course_id
                   )
                   AND semester = %s
                   AND year = %s;'''
                with connection.cursor() as cursor:
                    cursor.execute(query, [instructor.id, semester, year])
                    sec_result = dictfetchall(cursor)

                    context={
                        'form':form,
                        'sec_result':sec_result
                    }
                    return render(request, 'professor_sections.html', context)

            except Instructor.DoesNotExist:
                print("None found")
                
    else:
        form = Form()

    return render(request, 'professor_sections.html', {'form': form})

def student_list(request):
    if request.method == 'POST':
        form = StudentListForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            course= form.cleaned_data["course"]
            section = form.cleaned_data["section"]
            semester = form.cleaned_data["semester"]
            year = form.cleaned_data["year"]
            
            cursor = connection.cursor()
            try:
                instructor = Instructor.objects.get(name=name)
                query = '''
    SELECT Student.name, T1.student_id, Student.dept_name, Student.total_credits
    FROM Student
    JOIN (
        SELECT student_id
        FROM Takes
        WHERE course_id IN (
            SELECT course_id FROM Teaches WHERE teacher_id=%s)
        AND course_id = %s
        AND semester = %s
        AND sec_id = %s
        AND year = %s
    ) AS T1 ON Student.student_id = T1.student_id;
'''

                with connection.cursor() as cursor:
                    cursor.execute(query, [instructor.id,course, semester,section,year])

coreApp/templates/admin.html
{% extends 'base.html' %}

{% block title %}Admin Page{% endblock %}
{% block content %}
<div class="landingcontainer">
    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="/coreApp/static/images/prof.jpeg" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title" style="font-weight: bold;">Create List of Professors</h5>
          <p class="card-text">Create a comprehensive list of professors for administrative purposes. This action generates a report containing detailed information about all professors in the university.</p>
          <form method="post" action="{% url 'coreApp:prof_stats' %}">
            {% csrf_token %}
            <!-- Include any additional form fields here if needed -->
            <button class="button-primary" type="submit">Create</button>
        </form>        
        </div>
    </div>

    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="/coreApp/static/images/Clarkson.jpg" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title" style="font-weight: bold;">Generate Salaries By Department</h5>
          <p class="card-text">Generate salary statistics by department to analyze the distribution of salaries among different academic departments. This action helps in budget planning and resource allocation.</p>
          <form method="post" action="{% url 'coreApp:salary_statistics_by_department' %}">
            {% csrf_token %}
            <!-- Include any additional form fields here if needed -->
            <button class="button-primary" type="submit">Generate</button>
        </form>        
        </div>
    </div>

    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="/coreApp/static/images/sumona-mondal_1.jpg" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title" style="font-weight: bold;">Search for specific Professor</h5>
        <p class="card-text"></p>Perform a search to find information about a specific professor. This action allows you to retrieve performance data, teaching assignments, and other relevant details.</p>
          <form method="post" action="{% url 'coreApp:performance' %}">
            {% csrf_token %}
            <!-- Include any additional form fields here if needed -->
            <button class="button-primary" type="submit">Search</button>
        </form>        
        </div>
    </div>


    
    
   

{% endblock %}

coreApp/templates/base.html
<!-- base.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Django App{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
   
</head>
<body>
    <!-- Navigation bar -->
    
    <nav class="navbar navbar-expand-lg" id="navbar">
      <a class="navbar-brand" href="#">
        <img src="{% static 'images/logo.png' %}" width="130"  class="d-inline-block align-top" alt="">
          UMS
      </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav" id="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'landing' %}">Home</a>
            <a class="nav-item nav-link active" href="{% url 'admin' %}">Admin</a>
            <a class="nav-item nav-link active" href="{% url 'instructor' %}">Instructor</a>
            <a class="nav-item nav-link active" href="{% url 'student' %}">Student</a>
        
          </div>
          
      </nav>
   

    <!-- Main content area -->
    <div class="container mt-3" id="contain">
      <div class="bg">
        {% block content %}
        {% endblock %}
      </div>
        
    </div>
    

    <!-- Footer -->
    <footer class="footer" id="footer">
        <div class="container-fluid ">
          <p>&copy; 2024 Clarkson University. All rights reserved.</p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

coreApp/templates/course_section.html
{% extends 'base.html' %}

{% block title %}Student List{% endblock %}
{% block content %}
<div class="form-content">
    <h3>Course Section Offered</h3>
    <form method="post" action="{% url 'coreApp:course_section' %}">
        {% csrf_token %}
        
        {{form.as_p}}
        <button type="submit">SUBMIT</button>
    </form> <br>

</div>

<div class="dark-overlay" id="results">
    <div id="res">

    {%if course_result%}
    <h2 style="text-align: center;">Section Info</h2>

    <p>Department: {{department}}</p>
    <p>Semester: {{semester}}</p>
    <p>Year: {{year}}</p>
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th>Course ID</th>
                <th>Course Name</th>
            </tr>
        </thead>
        <tbody>
            {% for course in course_result %}
                <tr>
                    <td>{{ course.course_id }}</td>
                    <td>{{ course.title }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{%else%}
    <br>
    <div class="alert alert-danger" role="alert">
        No Information Found!!!
      </div>
   
{%endif%}
</div>
</div>
    
{% endblock %}

coreApp/templates/instructor.html
{% extends 'base.html' %}

{% block title %}Instructor Page{% endblock %}
{% block content %}
<div class="landingcontainer">
    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="/coreApp/static/images/Capstone_Course.jpeg.jpg.webp" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title" style="font-weight: bold;">List Course Sections</h5>
          <p class="card-text">List all course sections available in the university's database. This action provides an overview of current course offerings and enrollment status.</p>
          <form method="post" action="{% url 'coreApp:professor_sections' %}">
            {% csrf_token %}
            <!-- Include any additional form fields here if needed -->
            <button class="button-primary" type="submit">Generate List</button>
        </form>        
        </div>
    </div>

    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="/coreApp/static/images/85.jpeg" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title" style="font-weight: bold;">List Students</h5>
          <p class="card-text">List all students currently enrolled in the university. This action provides detailed information about each student, including personal....</p>
          <form method="post" action="{% url 'coreApp:student_list' %}">
            {% csrf_token %}
            <!-- Include any additional form fields here if needed -->
            <button class="button-primary" type="submit">Generate List</button>
        </form>        
        </div>
    </div>
</div>

{% endblock %}

coreApp/templates/performance.html
{%extends 'base.html'%}

{% block title %}Salary Stats{% endblock %}

{% block content %}
<div class="form-content">
    <h3>Seach Instructor</h3>
    <form method="post" action="{% url 'coreApp:performance' %}">
        {% csrf_token %}
        
        {{form.as_p}}
        <button type="submit">SUBMIT</button>
    </form>  <br>  
</div>
<div class="dark-overlay" id="results">
    <div id="res">
        <h2 style="text-align: center;">Instructor Info</h2>
        {%if result != -1%}
        <p>ID: {{id}}</p>
        <p>Name: {{name}}</p>
        <p>Semester: {{semester}}</p>
        <p>Year: {{year}}</p>
        <p> No. of section taught: {{row_section}}</p>
        <p>Capacity: {{row_capacity}}</p>
        <p> Funding: ${{funding}}</p>
        <p>Publishing: {{publishing}}</p>
    {%else%}
        <br>
        <div class="alert alert-danger" role="alert">
            No Information Found!!!
        </div>

    {%endif%}
    </div>
    
</div>


{% endblock %}

coreApp/templates/professor_sections.html
{%extends 'base.html'%}

{% block title %}SProfessor Section{% endblock %}

{% block content %}
<div class="form-content">
    <h3>List Course Sections</h3>
    <form method="post" action="{% url 'coreApp:professor_sections' %}">
        {% csrf_token %}
        
        {{form.as_p}}
        <button type="submit">SUBMIT</button>
    </form> <br>
    
</div>
<div class="dark-overlay" id="results">
    <div id="res">

{% if sec_result %}
<h2 style="text-align: center;">Course Section Info</h2>
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th>Course ID</th>
                <th>Section ID</th>
                <th>Semester</th>
                <th>Year</th>
                <th>Capacity</th>
            </tr>
        </thead>
        <tbody>
            {% for section_info in sec_result %}
                <tr>
                    <td>{{ section_info.course_id }}</td>
                    <td>{{ section_info.sec_id }}</td>
                    <td>{{ section_info.semester }}</td>
                    <td>{{ section_info.year }}</td>
                    <td>{{ section_info.capacity }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{%else%}
    <br>
    <div class="alert alert-danger" role="alert">
        No Information Found!!!
  </div>

{% endif %}
</div>
</div>
{% endblock %}

coreApp/templates/roster.html
{% extends 'base.html' %}

{% block title %}Roster{% endblock %}

{% block content %}
<div id="roster">
    
    <div id="sort">
        <form method="post" action="{% url 'coreApp:sort_prof_name' %}">
            {% csrf_token %}
            <!-- Include any additional form fields here if needed -->
            <button type="submit">Sort By Name</button>
        </form>
        <form method="post" action="{% url 'coreApp:sort_prof_dept' %}">
            {% csrf_token %}
            <!-- Include any additional form fields here if needed -->
            <button type="submit">Sort By Department</button>
        </form>
        <form method="post" action="{% url 'coreApp:sort_prof_salary' %}">
            {% csrf_token %}
            <!-- Include any additional form fields here if needed -->
            <button type="submit">Sort By Salary</button>
        </form>
    </div>
</div>

<div class="dark-overlay" id="results">
    <div id="res">
        <h2 style="text-align: center;">Instructors </h2>
    <table class="table table-hover table-bordered">
        <thead class="thead-light">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Department</th>
                <th>Salary</th>
            </tr>
        </thead>
        <tbody>
            {% for pro in prof %}
                <tr>
                    <td>{{ pro.id }}</td>
                    <td>{{ pro.name }}</td>
                    <td>{{ pro.dept_name }}</td>
                    <td>{{ pro.salary }}</td>
                    
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>

{% endblock %}

coreApp/templates/salary_stats.html
{% extends 'base.html' %}

{% block title %}Salary Stats{% endblock %}
{% block content %}
<div class="dark-overlay" id="results">
<div id="res">
    <h2 style="text-align: center;">Salary Stats by Department</h2>
    <table class="table table-hover table-bordered"">
        <thead>
            <tr>
                <th>Department</th>
                <th>Minimum Salary</th>
                <th>Maximum Salary</th>
                <th>Average Salary</th>
            </tr>
        </thead>
        <tbody>
            {% for stat in salary_stats_by_dept %}
                <tr>
                    <td>{{ stat.dept_name }}</td>
                    <td>${{ stat.min_salary }}</td>
                    <td>${{ stat.max_salary }}</td>
                    <td>${{ stat.avg_salary|floatformat:2 }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
{% endblock %}

coreApp/templates/student.html
{% extends 'base.html' %}

{% block title %}Student List{% endblock %}
{% block content %}
<form method="post" action="{% url 'coreApp:course_section' %}">
    {% csrf_token %}
    <!-- Include any additional form fields here if needed -->
    <button type="submit">course_section</button>
</form>

{% endblock %}

coreApp/templates/student_list.html
{% extends 'base.html' %}

{% block title %}Student List{% endblock %}
{% block content %}
<div class="form-content">
    <h3>List Students</h3>
    <form method="post" action="{% url 'coreApp:student_list' %}">
        {% csrf_token %}
        
        {{form.as_p}}
        <button type="submit">SUBMIT</button>
    </form> <br>

</div>

<div class="dark-overlay" id="results">
    <div id="res">
{%if name%}
    

    <p>Professor Name: {{name}}</p>
    <p>Course Name: {{course}}</p>
    <p>Year: {{year}}</p>
    <p>Semester: {{semester}}</p>
    <p>Section: {{section}}</p>

        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th>Student ID</th>
                    <th>Student Name</th>
                    <th>Department</th>
                    <th> Total Credits</th>
                </tr>
            </thead>
            <tbody>
                {% for stat in sec_result %}
                    <tr>
                        <td>{{ stat.student_id }}</td>
                        <td>{{ stat.name }}</td>
                        <td>{{ stat.dept_name }}</td>
                        <td>{{ stat.total_credits }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
{%else%}
        <br>
        <div class="alert alert-danger" role="alert">
            No Information Found!!!
          </div>
       
{%endif%}
</div>
</div>
{% endblock %}